### ISSUE TITLE
Shipping 0.2.0

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1717]
As much as possible I'd like to focus on getting 0.2.0 of nteract out ~~this next week~~ :soon: (I'll fix up the milestones shortly). If there's anything you think we need to cover before the 0.2.0 release, please comment here or assign it to the milestone.

* [x] Fix the codemirror unicode code point values interpretation https://github.com/nteract/nteract/issues/1706, done in https://github.com/nteract/nteract/pull/1840
* [x] shift-enter and ctrl-enter on markdown cells needs to put them back in view mode
* [x] when other cells are focused, markdown should go back to view mode (Fixed in #1846)
* [x] Fix scrolling behavior #1850

**Comment by maphew** [comment]
It would be good to have clear instructions on what the pre-reqs are for users (distinct from devs) - #1513

**Comment by rgbkrk** [comment]
Gosh, has it been _this long_ since May??!

At least a lot of things have been fixed since then. 😄 

Some of the big items that were blocking me on release before are now cleared up (npm 5, flow and immutable partially fixed up), so I'm hopeful about getting the fixes in that were mentioned above within this week.

**Comment by rgbkrk** [comment]
Alright, I think this is in a good state for me to try to package another release. It's definitely happening tonight... Probably after the kids go to bed though. 😄

**Comment by rgbkrk** [comment]
We're well past 0.2.0, time to close this one!
