### ISSUE TITLE
Shipping 0.2.1

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1851]
Must haves:

* [ ] Completely refine the close & save lifecycle #1147
* [ ] Base resolution (relative notebooks) #1720
* [ ] Trim down size #1849

That's about all I can think of for now. 😺

**Comment by rgbkrk** [comment]
Amusingly, I skipped straight to `0.3.0` because I wasn't sure if I was going to conflict with the demo `0.2.5`, etc. from the autoupdating. I'm going to transfer these items to a "Shipping 0.3.1" issue. 😝
