### ISSUE TITLE
Shipping 0.4.0

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1936]
Must haves:

* [ ] Completely refine the close & save lifecycle #1147
* [ ] Base resolution (relative notebooks) #1720
* [x] Trim down size #1849

That's about all I can think of for now. 😺 

Note: We can ship the `0.3.x` line with some of these, I mostly want to paint a target of what `0.4.0` could consist of.

**Comment by rgbkrk** [comment]
0.4.0 was shipped, closing this
