### ISSUE TITLE
Maintenance Wishlist

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1970]
Hey all, there have been some old parts of desktop that I'd love to revisit. I keep thinking about them as I touch various parts of the app. It's about time I outline what some of them are, either to document what I'm going to go after or see if others want to tackle some. Without further ado:

* [x] Collapse all the (notebook cell) reducers into one that are practically the same `setIn` operation on a cell with a different path. All the action creators will end up creating one kind of action for reduction, and it will simplify any additions to metadata changing. (#1971)
* [x] Merge the `metadata` reducer into the document reducer (which will involve changing the usage)
* [x] Delete the constants.js file, switch to literals. Since we're using flow, we can use the literal type names and last I checked was a requirement for proper flow typing.
* [x] Unify all the action flow types. We've duplicated them across `actions.js` and the reducers
* [x] Convert hover logic for the cell creator to CSS (#1972)
* [x] Convert hover logic for the cell / cell-toolbar to CSS (done by @aaronraff in #1975)

**Comment by rgbkrk** [comment]
~I'm going to tackle the first one I listed there, collapsing reducers.~ Done.

**Comment by aaronraff** [comment]
I would like to take up the last bullet! Is it still open?

**Comment by rgbkrk** [comment]
I'm started on it in #1974, if you want to work on it today that's cool with me! My next step was going to be setting up the hover region in CSS that would affect if the toolbar is shown and remove our current JS solution.

**Comment by aaronraff** [comment]
Okay, I changed the JS logic over to CSS for cell.js. Going to commit it later tonight, does that sound like what you are looking for?

**Comment by rgbkrk** [comment]
Sounds good to me! I'm looking forward to it. I'm flying today and need to do some writing anyways so I'm happy for you to take it over. Feel free to open the PR early and seek feedback or ask questions as soon as you're ready.

**Comment by rgbkrk** [comment]
Oh hey we finished all this.
