### ISSUE TITLE
nbextension roadmap

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2002]
At a high-level, the nbextension (located at `packages/nbextension`) should have feature parity (from a UI level) with the nteract desktop app (and Jupyter's menu system).

In order for us to make our next release we're going to need several things:

* [x] Create a menu matching the Jupyter menuing system, at least implementing what is currently a native menu in nteract desktop #2010
  * [x] Populate the kernelspecs into the menu
  * [x] Make each of the menu items trigger known actions
* [x] Launch and connect to the proper kernel when notebook file loaded
* [x] Pull in notebook state reducers into the nbextension from the desktop app
  * [x] `document` - High Priority
  * [x] `app` - High Priority
  * [x] `comms` - Low Priority
  * [x] `config` - Low Priority
* [ ] Pull in or rewrite redux epics into the nbextension from the desktop app
  * [x] `loading` - High Priority
  * [x] `saving` - High Priority
  * [x] `execute` - High Priority
  * [x] `kernel-launch` - High Priority
  * [x] `comm` - Low Priority
  * [x] `config` - Low Priority
  * [x] `github-publish` - Wishlist

**Comment by rgbkrk** [comment]
We did all this! 🎉  Hooray!
