### ISSUE TITLE
nteract v0.8.0 release checklist

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2645]
We are looking fit to ship, so I'm [running through the release steps](https://github.com/nteract/nteract/blob/master/RELEASING.md) right now.

* [x] `npm run dist && open applications/desktop/dist/mac/nteract.app`
* [x] choose an alliterative adjective for our scientist, Berliner
  * Burly Berliner
* [x] `npm run dist:all`
* [x] `lerna run prepublishOnly` (verification step across all packages)
* [x] `npm run verifyBeforePublish`
* [x] prepare release notes
* [x] make the actual release

**Comment by rgbkrk** [comment]
Uh oh, I might have gotten myself into a pickle with that electron upgrade. The `dist` copy works fine, the dev copy does not. The `NODE_MODULE_VERSION`s mismatch even though the ABI really is the same (all are node 8 here).

**Comment by rgbkrk** [comment]
### UI features

* Kernels now sorted by display name in the menu (#2591)
* Improve messaging about kernel state (#2628, #2495)
* Log "extra" stdout / stderr streams from kernel to chrome console (#2646)
* Theme aware title bar in the webapp (#2551, #2547, #2545)
* Clear pager on output clear (#2525)
* Always create block math if `$$` occurs in markdown (#2499)
* New Menu Items (webapp):
  * Halt Kernel (#2529)
  * Restart Kernel (#2528, #2512)
  * Unhide and Clear All Outputs (#2517, #2520, #2512)
  * Execute All (#2518, #2519)
* Improved menu look (webapp) (#2494)

### Stability

* Editor now tracks subscriptions and closes them (#2505)

### Accessibilty

* All octicon SVGs now have a `<title>` tag to describe their intent (#2587)

### New components

* Notebook selection menu (#2623)
  * Note: not integrated in any app yet

![select your kernel](https://user-images.githubusercontent.com/836375/36950332-60edb18e-1fa9-11e8-90e5-302fd010d55c.gif)

### Big repo changes

* No more `@nteract/types` module
* `@nteract/commuter-frontend` has moved into `@nteract/commuter` directly to simplify publishing releases (#2634)

### Developer Experience

* Electron is upgraded to 1.8.3 (#2632)
* Addressed (almost all) flow type misconfigurations -- you're more likely to have a safe and sane setup (#2563, #2570, #2571, #2572, #2573, #2581, #2583, #2584, #2588, #2594, #2595, #2600, #2605, #2607, #2606, #2609, #2611, #2612, #2613, #2621, #2539, #2529, #2515, #2507, #2501)
* Refactored core into a new "core state" that switches us to a `byRef` structure and relies heavily on selectors to get state (#2592, #2601, #2603, #2605, #2602, #2614, #2619, #2616, #2620, #2626, #2642, #2541, #2522, #2514, #2511, #2500, #2490, #2493)
* Extract core components into pure and connected (#2578)
* Webpack configurations are more unified across all apps using the nteract webpack configurator (#2593, #2597, #2599, #2627, #2622)
* Hooked up showcase with new monorepo-aware webpack setup (#2622)
