### ISSUE TITLE
nteract v0.8.1 release checklist

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2653]
This is a follow up release for a missing package dependency. I'm [running through the release steps](https://github.com/nteract/nteract/blob/master/RELEASING.md) right now.

## Precursors

* [x] Upgrade macOS
* [x] Upgrade xcode and make sure it can open...

## Actuals

* [x] `npm run dist && open applications/desktop/dist/mac/nteract.app`
* [x] choose an alliterative adjective for our scientist, Bernard
  * Bernese Bernard
* [x] `npm run dist:all`
* [X] `npm run verifyBeforePublish`
* […] `lerna publish`
* […] prepare release notes
* [ ] make the actual release

**Comment by rgbkrk** [comment]
During `npm run dist:all`:

```
nteract:   • building        target=zip arch=x64 file=dist/nteract-0.8.0-win.zip
nteract:   • building        target=nsis file=dist/nteract Setup 0.8.0.exe archs=x64 oneClick=false
nteract: Error: Exit code: null. Command failed: codesign --sign 357658D4990764C5489C6B21E4A09B4D1D1CC5BF /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/dist/nteract-0.8.0.dmg\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/builder-util/src/util.ts:124:16\n    at ChildProcess.exithandler (child_process.js:282:5)\n    at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    at maybeClose (internal/child_process.js:925:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
nteract: From previous event:\n    at DmgTarget.signDmg (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/dmg-builder/out/dmg.js:277:11)\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/dmg-builder/src/dmg.ts:63:16\n    at Generator.next (<anonymous>)
nteract: From previous event:\n    at DmgTarget.build (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/dmg-builder/out/dmg.js:243:11)\n    at taskManager.addTask.default.map.it (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/platformPackager.ts:122:67)
nteract: From previous event:\n    at MacPackager.packageInDistributableFormat (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/platformPackager.ts:122:23)\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/macPackager.ts:95:26\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)
nteract: From previous event:\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/macPackager.ts:95:10\n    at Generator.next (<anonymous>)
nteract: From previous event:\n    at MacPackager.pack (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/out/macPackager.js:209:11)\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/packager.ts:368:24\n    at Generator.next (<anonymous>)\n    at xfs.mkdir.er (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)\n    at FSReqWrap.oncomplete (fs.js:135:15)
nteract: From previous event:\n    at Packager.doBuild (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/out/packager.js:438:11)\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/packager.ts:312:52
nteract: From previous event:\n    at Packager._build (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/out/packager.js:382:11)\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/packager.ts:274:23\n    at Generator.next (<anonymous>)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)
nteract: From previous event:\n    at Packager.build (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/out/packager.js:338:11)\n    at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/src/index.ts:50:40\n    at Generator.next (<anonymous>)
nteract: From previous event:\n    at build (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/out/index.js:47:21)\n    at build (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/src/builder.ts:229:10)\n    at then (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/src/cli/cli.ts:48:33)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)
nteract: From previous event:\n    at Object.args [as handler] (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/src/cli/cli.ts:48:33)\n    at Object.runCommand (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)\n    at Object.parseArgs [as _parseArgs] (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/yargs/yargs.js:1042:24)\n    at Object.get [as argv] (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)\n    at Object.<anonymous> (/Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/node_modules/electron-builder/src/cli/cli.ts:42:15)\n    at Module._compile (module.js:635:30)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n    at Function.Module.runMain (module.js:676:10)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3
```

It didn't fail while building it, so _maybe_ things are ok? I just happened to notice it in the logs.

**Comment by lgeiger** [comment]
Looks like the codesign failed.

**Comment by rgbkrk** [comment]
Wow, that is much more readable on GitHub than it was on my build box. I'll check to see if the upgrade to my system last night is the culprit and make sure xcode is up to date and A-OK.

**Comment by rgbkrk** [comment]
Oh ha, I just broke my build via the homebrew upgrade now that `python` is `python3`.

**Comment by rgbkrk** [comment]
```
npm config set python python2.7
```

to the rescue

**Comment by rgbkrk** [comment]
Woo, after launching `XCode` code signing works again. 🎉

**Comment by rgbkrk** [comment]
# Release Notes

`redux-observable` was missing from dependencies in `@nteract/core`. This fixes the latest releases of `@nteract/commuter` and `@nteract/notebook-preview`.

**Comment by rgbkrk** [comment]
NOOOOOOOOO


```
Retrying failed publish: nteract
```

**Comment by rgbkrk** [comment]
I wish the `lerna publish` would show me what's going on as to why... If and when I run this again, I'm going to tack on `--stream` and hope it gives me detail.

**Comment by rgbkrk** [comment]
```
 (master=) kyle@meh ~/code/src/github.com/nteract/nteract$ lerna publish
lerna info version 2.8.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with @nteract/commutable@4.0.0.
lerna info Checking for prereleased packages...
? Select a new version for @nteract/core (currently 4.0.0) Patch (4.0.1)
? Select a new version for @nteract/notebook-preview (currently 7.0.0) Patch (7.0.1)
? Select a new version for @nteract/commuter (currently 5.0.0) Patch (5.0.1)
? Select a new version for nteract (currently 0.8.0) Patch (0.8.1)
? Select a new version for @nteract/notebook-on-next (currently 2.0.2) Patch (2.0.3)
? Select a new version for @nteract/play (currently 1.4.2) Patch (1.4.3)
? Select a new version for @nteract/showcase (currently 0.1.13) Patch (0.1.14)
? Select a new version for nteract-on-jupyter (currently 1.5.0) Patch (1.5.1)

Changes:
 - @nteract/core: 4.0.0 => 4.0.1
 - @nteract/notebook-preview: 7.0.0 => 7.0.1
 - @nteract/commuter: 5.0.0 => 5.0.1
 - nteract: 0.8.0 => 0.8.1
 - @nteract/notebook-on-next: 2.0.2 => 2.0.3
 - @nteract/play: 1.4.2 => 1.4.3
 - @nteract/showcase: 0.1.13 => 0.1.14
 - nteract-on-jupyter: 1.5.0 => 1.5.1

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published @nteract/core
lerna ERR! publish Retrying failed publish: nteract
lerna ERR! publish Retrying failed publish: nteract
⸨  ░░░░░░░░░░░░░░░░⸩ ⠙ npmPublish: ERR! publish Retrying failed publish: nteract
⸨  ░░░░░░░░░░░░░░░░⸩ ⠙ npmPublish: ERR! publish Retrying failed publish: nteract
⸨  ░░░░░░░░░░░░░░░░⸩ ⠙ npmPublish: ERR! publish Retrying failed publish: nteract
⸨  ░░░░░░░░░░░░░░░░⸩ ⠙ npmPublish: ERR! publish Retrying failed publish: nteract
lerna ERR! publish Retrying failed publish: nteract
lerna ERR! publish Retrying failed publish: nteract
lerna ERR! publish Ran out of retries while publishing nteract Error: Command failed: npm publish --tag latest
lerna ERR! publish npm ERR! "toString()" failed
lerna ERR! publish
lerna ERR! publish npm ERR! A complete log of this run can be found in:
lerna ERR! publish npm ERR!     /Users/kyle/.npm/_logs/2018-03-08T18_43_09_199Z-debug.log
lerna ERR! publish
lerna ERR! publish     at Promise.all.then.arr (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR! publish     at <anonymous>
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm publish --tag latest
lerna ERR! npm ERR! "toString()" failed
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/kyle/.npm/_logs/2018-03-08T18_43_09_199Z-debug.log
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ stack: 'Error: Command failed: npm publish --tag latest\nnpm ERR! "toString()" failed\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/kyle/.npm/_logs/2018-03-08T18_43_09_199Z-debug.log\n\n    at Promise.all.then.arr (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/lerna/node_modules/execa/index.js:236:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
  exitCode: 1 }
```

**Comment by rgbkrk** [comment]
```
$ cat /Users/kyle/.npm/_logs/2018-03-08T18_43_09_199Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/kyle/.nvm/versions/node/v8.9.3/bin/node',
1 verbose cli   '/Users/kyle/.nvm/versions/node/v8.9.3/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--tag',
1 verbose cli   'latest' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session 35b9b3808186f827
5 verbose publish [ '.' ]
6 info lifecycle nteract@0.8.1~prepublish: nteract@0.8.1
7 info lifecycle nteract@0.8.1~prepare: nteract@0.8.1
8 info lifecycle nteract@0.8.1~prepublishOnly: nteract@0.8.1
9 info lifecycle nteract@0.8.1~prepack: nteract@0.8.1
10 info lifecycle nteract@0.8.1~postpack: nteract@0.8.1
11 verbose getPublishConfig { access: 'public' }
12 silly mapToRegistry name nteract
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'nteract',
15 silly mapToRegistry   name: 'nteract',
15 silly mapToRegistry   escapedName: 'nteract',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri https://registry.npmjs.org/nteract
17 verbose publish registryBase https://registry.npmjs.org/
18 silly publish uploading /var/folders/d6/28470sgd1zd5d8l86z_b26lm0000gn/T/npm-10906-8292fef5/tmp/fromDir-6b74ab48/package.tgz
19 verbose stack Error: "toString()" failed
19 verbose stack     at stringSlice (buffer.js:578:45)
19 verbose stack     at Buffer.toString (buffer.js:633:10)
19 verbose stack     at RegClient.putFirst (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:103:23)
19 verbose stack     at /Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:54:14
19 verbose stack     at ConcatStream.<anonymous> (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/index.js:36:43)
19 verbose stack     at emitNone (events.js:111:20)
19 verbose stack     at ConcatStream.emit (events.js:208:7)
19 verbose stack     at finishMaybe (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:607:14)
19 verbose stack     at endWritable (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:615:3)
19 verbose stack     at ConcatStream.Writable.end (/Users/kyle/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:571:41)
19 verbose stack     at ReadStream.onend (_stream_readable.js:595:10)
19 verbose stack     at Object.onceWrapper (events.js:313:30)
19 verbose stack     at emitNone (events.js:111:20)
19 verbose stack     at ReadStream.emit (events.js:208:7)
19 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
19 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
20 verbose cwd /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop
21 verbose Darwin 17.4.0
22 verbose argv "/Users/kyle/.nvm/versions/node/v8.9.3/bin/node" "/Users/kyle/.nvm/versions/node/v8.9.3/bin/npm" "publish" "--tag" "latest"
23 verbose node v8.9.3
24 verbose npm  v5.5.1
25 error "toString()" failed
26 verbose exit [ 1, true ]
```

**Comment by rgbkrk** [comment]
Running `lerna publish --force-publish=@nteract/core`, running into the same failure... 🙀

**Comment by rgbkrk** [comment]
Whoa, I just noticed we can publish to a prerelease tag using `--npm-tag`:

https://www.npmjs.com/package/lerna#--npm-tag-tagname

**Comment by rgbkrk** [comment]
Ran a semi-release by running:

```
lerna publish --force-publish=@nteract/core --ignore nteract
```

That appears to be working well. Since I'm in no rush to get a new copy of nteract desktop out the door, I'll hope this goes well... 😨

**Comment by rgbkrk** [comment]
The super bad thing about `--ignore` is that it doesn't just skip publishing -- it also skips bumping up the version numbers. 😠

**Comment by rgbkrk** [comment]
The desktop app itself doesn't _actually_ need to be published to `npm`, but we do want to bump the version and run our `publish` command (that runs the electron builder flow). Something needs to change with our setup.

**Comment by rgbkrk** [comment]
Time to run through those verification steps again... 😂

**Comment by rgbkrk** [comment]
I've changed `nteract` desktop to a `private` package in its `package.json` to make this simpler, and I'll be running the shipping steps for desktop separately now.

**Comment by rgbkrk** [comment]
No more nteract desktop publishing breaking the publishing of the monorepo! It's now a separate step to ease our pain.

```
lerna run publish # version numbers bump here
lerna run ship --scope nteract --stream # try to really ship the desktop app
```
