### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2980]
For the nteract desktop 0.9.0 release and the nteract-on-jupyter release, there are several items I'd like tackled:

* ~[x] Upgrade [monaco editor webpack plugin](https://github.com/Microsoft/monaco-editor-webpack-plugin) since it now handles `__webpack_public_path__`~: https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/7
* [x] Determine what's making some outputs re-render poorly. This definitely affects vega. #2984
* [x] Update changelog with all the latest jupyter extension changes /cc @alexandercbooth 
* [x] Help with @emeeks / semiotic / roughjs release (Data Explorer!)

**Comment by rgbkrk** [comment]
I'm going to skip on fixing #2984 in favor of getting a release out since so many are requesting it. I'll work on the perf issue right after.

**Comment by rgbkrk** [comment]
I may have to say that the monaco editor webpack plugin is upgraded at this point, though non-functional: #2992

**Comment by rgbkrk** [comment]
Oops! I noticed I linked #2990 as the blocker above when it was really #2984. 😅

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
