### ISSUE TITLE
Reduce unnecessary rerenders of editor component in notebook

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#3434]
Currently all code editors are rerendered on every key press or focus change:
![perf](https://user-images.githubusercontent.com/13285808/46870764-d5c45a00-ce2f-11e8-94db-977740644680.gif)

I think there are a few things that may be the culprits:
- [mapDispatchToProps](https://github.com/nteract/nteract/blob/master/packages/notebook-app-component/src/editor.js#L41-L58) and [mapDispatchToCellProps](https://github.com/nteract/nteract/blob/master/packages/notebook-app-component/src/notebook-app.js#L115-L130) creates a new function on every prop change since it relies on the [ownProps](https://github.com/reduxjs/react-redux/blob/master/docs/api.md#arguments)
- [kernelStatus](https://github.com/nteract/nteract/blob/master/packages/editor/src/index.js#L44) often changes when requesting a code completion
- [codeMirrorOptions](https://github.com/nteract/nteract/blob/master/packages/notebook-app-component/src/notebook-app.js#L193) creates a new object when passing it to the editor props

We should definitely improve this component to improve the responsiveness in larger notebooks.

**Comment by jameskoch** [comment]
(Nevermind, you already found this) I happen to be poking around code completion (#3314) and noted this relevant note:

https://github.com/nteract/nteract/blob/a9719367c974737be3879f76e5cc3d904595d36f/packages/editor/src/index.js#L41-L43

**Comment by rgbkrk** [comment]
This greatly saddens me as I fixed this particular issue for nteract web earlier this year. 😭  Clearly I need to work on implementing tests for perf like this, as the editor is the main component for each cell.

**Comment by jameskoch** [comment]
FWIW, it looks like kernelStatus changes aren't flowing in all that quickly, at least in desktop.

1. Start from new notebook, not-connected-to-a-kernel.
2. Type some characters in the default/first cell. Observe via breakpoint in `keyupEventsSubscriber` that auto-completion is not firing due to kernelStatus === "not connected".
3. Start a kernel via Runtime menu.
4. Observe that auto-completion still not happening, kernelStatus is unchanged.
5. Restart kernel.
6. Observe that auto-completion still not happening, kernelStatus is unchanged.

Proximate cause: [This line](https://github.com/nteract/nteract/blob/a9719367c974737be3879f76e5cc3d904595d36f/packages/editor/src/index.js#L192) is reading kernelStatus out of props only once, at mount time.

**Comment by rgbkrk** [comment]
One thing I see we need to get a handle on is all usage of objects created at render time like this:

https://github.com/nteract/nteract/blob/master/packages/notebook-app-component/src/notebook-app.js#L193-L196

Those will cause a re-render even if the options are the same in many cases (though we do check all the options in the editor component itself).

**Comment by lgeiger** [comment]
> Those will cause a re-render even if the options are the same in many cases (though we do check all the options in the editor component itself).

That makes me think if we should also add this as an ESLINT rule: https://github.com/cvazac/eslint-plugin-react-perf/blob/master/docs/rules/jsx-no-new-object-as-prop.md

**Comment by rgbkrk** [comment]
That'd be great!

**Comment by lgeiger** [comment]
I think the root problem is that `mapDispatchToProps` relies on `ownProps` in several places. This means it will be reinvoked [every time the `props` change](https://github.com/reduxjs/react-redux/blob/master/docs/api.md#arguments):
> If your mapDispatchToProps function is declared as taking two parameters, it will be called with dispatch as the first parameter and the props passed to the connected component as the second parameter, and will be re-invoked whenever the connected component receives new props.

I guess it then passes down new dispatch functions to our components, thus breaking shallow compare of `props`.

**Comment by rgbkrk** [comment]
Gross. That completely relates to all the `contentRef` stuff that got brought in too then. I've got to do some digging on that. Thank you for surfacing this @lgeiger.

**Comment by rgbkrk** [comment]
Ok, @lgeiger and I did some talking on this one and some digging through react-redux docs. This thread is the most helpful: https://github.com/reduxjs/react-redux/pull/348

Basically, we need to switch to a makeMapStateToProps that captures the `contentRef` (sometimes the `appBase` in some cases) and get rid of all use of `ownProps`. It would look something like this:

```js
function makeMapStateToProps(initialState, initialOwnProps) {
  const contentRef = initialOwnProps.contentRef
  return function mapStateToProps(state) {
    return {
      content: selectors.content(state, { contentRef })
    }
  }
}

connect(makeMapStateToProps)(File);
```

Now that we have it outlined well I'm thinking this is `new-contributor-friendly` or at least a good problem for folks to tackle if they:

* Are comfortable with Redux
* Want to learn about our state structure
* Make a significant impact to the performance of the app

**Comment by rgbkrk** [comment]
I've now kicked off the `makeMapStateToProps` work in https://github.com/nteract/nteract/pull/4009.

All the files we need to convert:

* [x] `packages/notebook-app-component/src/toolbar.tsx` #4010
* [x] `packages/notebook-app-component/src/editor.tsx` #4015
* [x] `packages/notebook-app-component/src/status-bar.tsx` #4010
* [ ] `packages/notebook-app-component/src/notebook-app.tsx` #4068 
* [ ] `applications/desktop/src/notebook/menu.ts`
* [x] `applications/jupyter-extension/nteract_on_jupyter/app/contents/index.tsx` #4009
* [x] `applications/jupyter-extension/nteract_on_jupyter/app/contents/file/index.tsx` #4009
* [x] `applications/jupyter-extension/nteract_on_jupyter/app/contents/file/text-file.tsx` #4010
* [x] `applications/jupyter-extension/nteract_on_jupyter/app/contents/directory.tsx` #4010

**Comment by rgbkrk** [comment]
Note: I just did a `ack -l ownProps` so if the ownProps arg is named something else I didn't surface those.

**Comment by rgbkrk** [comment]
I wish there was some way for us to accept changes to the options object and just pass that to codemirror entries directly without a re-render.

**Comment by rgbkrk** [comment]
With #4068, only `applications/desktop/src/notebook/menu.ts` remains untapped for makeMapStateToProps changes.

**Comment by rgbkrk** [comment]
Helpful article: https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab
