### ISSUE TITLE
Migrate from flow to typescript

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3462]
We've faced the pain of maintaining flow definitions and trying to help with `flow-typed` long enough. It's about time we switch to typescript. Many of us have seen the writing on the wall and keep talking about it. The community just isn't in flow. Time to take action.

Since we're on babel 7, we can start incrementally adopting typescript package by package.

For larger packages like `@nteract/core` we might want to try https://medium.com/entria/incremental-migration-to-typescript-on-a-flowtype-codebase-515f6490d92d

If you'd like to help out, start with a single small package. We'll use the first one (#3465) as a reference to the rest.

-------

We are _all_ done with the packages\* except for the data explorer, styles, styleguide components, and webpack configurator. Data explorer has an in-progress PR #3874. `styles` probably isn't worth it. Styleguide components... could probably be brought down out of `packages` as its just for the docs. That or we make those official components in some way. Webpack configurator may not be necessary soon as pointed out by @captainsafia as part of the nteract play PR.

As for application conversion:

* [x] Desktop PR: #3900 
* [x] Jupyter Extension: Started in #3914, surfaced errors in #3917
* [x] Play: Done in #3842
*  ~Commuter: not started~ migrating back to nteract/commuter

Additional efforts:

* [x] [adapt our docgen setup to using typescript](https://github.com/styleguidist/react-docgen-typescript)

**Comment by rgbkrk** [comment]
In https://github.com/Microsoft/TypeScript-Babel-Starter/issues/1 , @DanielRosenwasser offered some suggestions.

@captainsafia and I talked about doing something promotional in open source, possibly to give a sticker for each file switched over to typescript.

**Comment by jdfreder** [comment]
s/each file/each package/ ? Each file would be a boat load of stickers!!

... although I have 0 nteract stickers right now.

Anyways, todo:

- [x] ansi-to-react
- [x] commutable
- [x] connected-components
- [x] core
- [x] directory-listing
- [x] display-area
- [x] dropdown-menu
- [x] editor
- [x] enchannel-zmq-backend
- [x] fs-observable
- [x] gatsby-transformer-ipynb
- [x] host-cache
- [x] iron-icons
- [x] jupyter-widgets
- [x] logos
- [x] markdown
- [x] mathjax
- [x] messaging
- [x] monaco-editor
- [x] notebook-app-component
- [x] notebook-preview
- [x] notebook-render
- [x] octicons
- [x] outputs
- [x] presentational-components
- [x] records
- [x] rx-binder
- [x] rx-jupyter
- [x] styleguide-components #3962
- [x] styles (deleted in https://github.com/nteract/nteract/pull/3959)
- [x] timeago
- [x] transform-dataresource
- [x] transform-geojson
- [x] transform-model-debug
- [x] transform-plotly
- [x] transform-vdom
- [x] transform-vega
- [x] transforms-full
- [x] transforms
- [x] vega-embed2 (removed in #3468)
- [ ] webpack-configurator

**Comment by rgbkrk** [comment]
Gosh Jon, you better kick this off so you get some stickers. There are ~518 relevant js files.

```
$ find . -name "*.js" | grep -v node_modules | grep -v "flow-typed" | wc -l
     518
```

**Comment by rgbkrk** [comment]
We could probably prioritize the above list too.

**Comment by jdetle** [comment]
![nteract sticker](https://user-images.githubusercontent.com/10944582/47221317-aa82c300-d379-11e8-968c-6403ac8afc93.png)

^ Would this be a fun sticker?

**Comment by jdetle** [comment]
The idea being that we fill in whatever the package name is with a sharpie when we send it.

**Comment by rgbkrk** [comment]
We are off to the races in #3465 thanks to @jdetle!

**Comment by rgbkrk** [comment]
I personally never like those kinds of stickers (or that saying), so I wouldn't apply it to my laptop. Some folks find that fun though.

**Comment by jdetle** [comment]
Okay, just a thought :D

**Comment by hydrosquall** [comment]
This is something I've started doing on some internal projects as well, so I'll start looking at some of these next time I pick up an open-source ticket :)

**Comment by lgeiger** [comment]
We should write a step by step guide and a checklist to guide the conversion of packages. This is inspired by the super detailed package migration issues on the Atom repo: https://github.com/atom/atom/issues/18286

**Comment by jdetle** [comment]
What were our steps?
1. Establish a tsconfig.json that extends from a root level config.
2. Add typescript and pertinent @types as a dev dependency in the root level directory with `yarn add -dev typescript @types/react ... -W`
3. Attempt to type a package that does not have any dependencies from the monorepo
4. Replace that packages `build` command with `tsc`
5. Rewrite src/*.js in typescript
	a. Import all monorepo types from our root level `types/` directory.
	b. Establish as-strict-as-possible compiler options, if an imported package needs to be any because it is currently not typed by us, dont worry if you have to allow an implicit any while you're migrating.
	c. Try to minimize urges to introduce breaking changes into the code.
	d. Leverage types from imported code as often as possible
6. Work your way up the dependency graph inside `packages/`, attempt to tighten strictness as we go. 
8. When all package work is done, type `applications/` and other third-party tools using nteract packages.

**Comment by rgbkrk** [comment]
Since we've got to handle it in phases, we want sections for different personas:

* "I'd like to help convert a single package" -- the most important
* "I'd like to help switch an _app_ to typescript" -- we haven't tackled this yet
* Status board of which packages to convert

**Comment by rgbkrk** [comment]
We are _all_ done with the packages\* except for the data explorer, styles, styleguide components, and webpack configurator. Data explorer has an in-progress PR #3874. `styles` probably isn't worth it. Styleguide components... could probably be brought down out of `packages` as its just for the docs. That or we make those official components in some way. Webpack configurator may not be necessary soon as pointed out by @captainsafia as part of the nteract play PR.

As for application conversion:

* Desktop PR: #3900 
* Jupyter Extension: Started in #3914, surfaced errors in #3917
* Play: Done in #3842
* Commuter: not happening (now), getting moved back out to nteract/commuter

**Comment by rgbkrk** [comment]
I'm going to look into writing our [webpack configs in typescript](https://webpack.js.org/configuration/configuration-languages/#typescript).

**Comment by rgbkrk** [comment]
Actually, tabling that and going after some flow removals for a moment.

**Comment by rgbkrk** [comment]
Desktop still needs the "main" side converted over to typescript.

**Comment by rgbkrk** [comment]
All done! Thank you everyone, this was quite the endeavor!
