### ISSUE TITLE
UI review of latest release

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#4148]
@stormpython and I did a review of the current UI to see what needs some extra polish.

## Menu component

Distance between menus

![screen shot 2019-01-30 at 10 34 51 am](https://user-images.githubusercontent.com/836375/52003921-b4d55280-247a-11e9-966b-0230494d8d02.png)

When rename modal shown, menu bar doesn't fade out:

![screen shot 2019-01-30 at 10 34 11 am](https://user-images.githubusercontent.com/836375/52003893-9f602880-247a-11e9-9b98-70a23c5be46e.png)

It's possible instead of fixing this component directly we create it with blueprint.js components.

## Title Bar

Title bar shouldn't be pure white

![screen shot 2019-01-30 at 10 35 55 am](https://user-images.githubusercontent.com/836375/52003969-d9c9c580-247a-11e9-8f07-a3532132612b.png)

Likely missing some style -- this was the old:

```
header.jsx-3942920302 {
    background-color: hsl(0, 0%, 94%));
    box-sizing: border-box;
}
```

# Memory leak with our use of ReactDOM in Completions:

![screen shot 2019-01-30 at 10 42 20 am](https://user-images.githubusercontent.com/836375/52004364-be12ef00-247b-11e9-9343-16e43fa66008.png)
![screen shot 2019-01-30 at 10 41 43 am](https://user-images.githubusercontent.com/836375/52004377-c539fd00-247b-11e9-9f71-cd23e0d13045.png)

# Kernel cards missing style

Left: last release
Right: current release

![screen shot 2019-01-30 at 10 44 50 am](https://user-images.githubusercontent.com/836375/52004516-1ea22c00-247c-11e9-91c7-35005488535a.png)

# Cell Toolbar

It's... missing? How'd we... miss this?

![screen shot 2019-01-30 at 11 29 08 am](https://user-images.githubusercontent.com/836375/52006976-4a281500-2482-11e9-8b8f-43362cf34a69.png)

# Directory listing

We should show directories, notebooks, then files in that order.

**Comment by willingc** [comment]
- [ ]  [ Menu: Gap between toolbar and dropdown #4149 ](/nteract/nteract/issues/4149)

- [ ] [ Menu: toolbar menu shown when rename modal open #4150 ](/nteract/nteract/issues/4150)
 Closed
- [x]  [Title Bar: shouldn't be pure white #4151 ](/nteract/nteract/issues/4151)
- [ ] [ Directory Listing: should show directories, notebooks, then files #4155 ](/nteract/nteract/issues/4155)
- [x]  [ Cell toolbar is missing #4154 ](/nteract/nteract/issues/4154)
- [x] [ Kernel cards missing styles #4153 ](/nteract/nteract/issues/4153)
- [ ]  [ Memory Leak with use of ReactDOM in autocompletions #4152](/nteract/nteract/issues/4152)

**Comment by rgbkrk** [comment]
Oooh, thank you for making the checklist Carol!

I'm going after #4149 and #4150 this week.

**Comment by captainsafia** [comment]
I'll go ahead and close this since the sub-issues here are tracked elsewhere.
