### ISSUE TITLE
Meta-issue: Tackle the TODOs in packages

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4780]
**Context**
We've got quite a few to-dos sprinkled across the nteract codebase. As is the case we these things sometimes, we haven't gotten around to resolving them.

We had a to-do bot that would open issues for any to-dos that were placed in the code when a PR was merged. However, these issues have gone stale/been auto-closed/etc over the past few years. I'm starting this issue as a more concerted effort to address these to-dos. I'll be tagging this issue as "new-contributor-friendly" since I think a few of these to-dos meet that bar.

Note: the list below is only the todos that are in the packages, not the applications.

If you are a new contributor and have any questions about these TODOs, feel free to post a comment.

**List of TODOs**

-  [ ] Remove `createMessage` and `createExecuteRequest` functions from @nteract/messaging ([link](https://github.com/nteract/nteract/blob/master/packages/messaging/src/index.ts#L13-L24))
- [ ] Improve types for `executeReply` function in @nteract/messaging ([link](https://github.com/nteract/nteract/blob/master/packages/messaging/src/messages.ts#L313))
- [ ] Remove top-level kernel from state model ([link](https://github.com/nteract/nteract/blob/master/packages/reducers/src/core/index.ts#L10))
- [ ] Update `acceptPayloadMessage` to take `JupyterMessage` as payload instead of custom type ([link](https://github.com/nteract/nteract/blob/master/packages/actions/src/actions/index.ts#L202))
- [ ] Set appropriate `role` attribute on modal for accessibility ([link](https://github.com/nteract/nteract/blob/master/packages/connected-components/src/modal-controller/about-modal.tsx))
- [ ] Remove notification system from packages ([link](https://github.com/nteract/nteract/blob/master/packages/epics/src/kernel-lifecycle.ts#L281))
- [ ] Create key paths for display IDs when cell is paster ([link](https://github.com/nteract/nteract/issues/1377))
- [ ] Handle storage evens in @binder/host-cache ([link](https://github.com/nteract/nteract/issues/3037))
- [ ] Handle payload message for creating new cell in `createCellBelow` reducer ([link](https://github.com/nteract/nteract/blob/master/packages/reducers/src/core/entities/contents/notebook.ts#L616))

**Comment by logankilpatrick** [comment]
Hey, what should the deprecated functions be replaced with for this task "Remove `createMessage` and `createExecuteReques`t functions from `@nteract/messaging` "

**Comment by captainsafia** [comment]
@logankilpatrick Thanks for your interest!

The `createExecuteRequest` function should be replaced with calls to `executeRequest` which is defined in `messages.ts` of the `@nteract/messaging` package.

The `createMessage` function should be replaced with a type-specific invocation to one of the functions in `messages.ts`. For example, `createMessage('shutdown_request')` should be replaced with `shutdownRequest()`. If there is not a message creator for a specific message type, it should be added.

Let me know if you need more info!
