### ISSUE TITLE
The road to @nteract/web beta

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4956]
Following up on the work introduced in #4925, I wanted to draft a roadmap that outlined the goals and future of this project.

**Goals**
- Provide a web-based nteract experience that is freely available to folks at an nteract-based domain
- Improve the experience for front-end development on nteract as users no longer need to set up local Jupyter instances
- Eventually move towards a common app codebase for both the web and desktop app, enabled by frameworks like [nextron](https://github.com/saltyshiomix/nextron)
- Provide a flexible, compute protocol agnostic application that folks can build interactive computing apps on top off
- Deprecate the nteract Jupyter extension in favor of the nteract web app

**Tasks**
- [x] Implement sidebar component for browsing multiple files
- [x] Implement Binder config component for configuring target Binder instance
- [ ] Deploy beta of nteract web app to zeit now
- [ ] Implement KernelProvider model as outlined in #4902 
- [ ] Unify nteract web and desktop app code bases

**Comment by willingc** [comment]
I've gone ahead and pinned this issue @captainsafia as a strategic issue :smile:

**Comment by jabbera** [comment]
What does this mean for those of use who use nteract as part of a jupyterhub installation (specifically on a k8s cluster)? Will there be a similar offering?

**Comment by captainsafia** [comment]
> What does this mean for those of use who use nteract as part of a jupyterhub installation (specifically on a k8s cluster)? Will there be a similar offering?

The existing published version of the nteract Jupyter extension will continue to work although it is no longer supported. The current plan is to consolidate nteract web and the desktop app. There's no plans to bring back the Jupyter extension although it should be possible to repurpose the existing code and the new model to get something working.

Let me know if you have any follow-up questions/

**Comment by jabbera** [comment]
Thanks! Hopefully there is a comparable offering at some point. Hosted notebook environments that scale horizontally based on active users is key to our use case.

**Comment by ramantehlan** [comment]
@captainsafia Do you think the nteract web beta is ready for release? 
I think we can release it and let the community start using it.

**Comment by captainsafia** [comment]
@ramantehlan I think we probably want to do a round of testing/QA before that and also figure out some sort of CI for the deployment.

We can track that work in a separate issue. Would you be interested in creating it and identifying some scenarios to test?

**Comment by ramantehlan** [comment]
@captainsafia Sure, I will create the issue for the testing and for deployment pipeline.
