### ISSUE TITLE
Rendering notebooks as static documents

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#61]
This isn't so much of a concern for the Electron notebook itself. This is more about how the notebook gets presented when sharing on the web (converted to HTML, no kernel backed compute). As much as possible, we need to make sure that components which are pure can be extracted. Thus far, the primary ones have been:
- https://github.com/nteract/react-jupyter-display-area
- https://github.com/nteract/transformime-react

It makes a good bit of sense that Cell isn't, since we're keyed into editor changes. In order for us to have full parity with nbviewer and the notebook we're going to need more implemented within our other projects:
- [ ] Handle old notebook versions - https://github.com/nteract/commutable/issues/8
- [x] Console text as React Components - https://github.com/nteract/react-jupyter-display-area/issues/1
- [x] Maths - https://github.com/nteract/nteract/issues/99
- [x] Sanitization or sandboxing of HTML/JavaScript embedded in notebooks - https://github.com/nteract/react-jupyter-display-area/issues/6

Another piece that needs to be explored is:
- [ ] Prismjs input segments (instead of CodeMirror) for CodeCells

Roughly speaking, the static rendering component starts to look like this, complete with custom transforms (swapping out the defaults used in https://github.com/nteract/transformime-react):

``` jsx
import { transforms } from 'transformime-react';
import Display from 'react-jupyter-display-area';

const IFramedHTML = React.createClass({
  render: function() {
    return (
      <iframe ...>
         <somehow {this.props.data} />
      </iframe>
    );
  }
});

const myTransforms = transforms.set('text/html', IFramedHTML);

...

const StaticCodeCell = React.createClass({
  render: function() {
    return (
      <div>
        <PrismCode>
          {this.props.cell.get('source')}
        </PrismCode>
        <Display transforms={myTransforms}
                 outputs={this.props.cell.get('outputs')} />
      </div>
    );
  }
});
```

**Comment by rgbkrk** [comment]
One approach for sanitization: https://github.com/nteract/nteract/pull/192

**Comment by rgbkrk** [comment]
We've now got this as the [notebook preview](https://github.com/nteract/notebook-preview) package!
